### ISSUE TITLE
REMOTE_AUTH_DEFAULT_PERMISSIONS will not start

### ISSUE THREAD

**Issue by gwmiii** [linuxserver/docker-netbox#39] opened 2022-07-19 09:05 UTC
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

in file "/app/netbox/netbox/netbox/configuration.py" line 246

REMOTE_AUTH_DEFAULT_PERMISSIONS = REMOTE_AUTH_DEFAULT_PERMISSIONS} 
i think it shoud be REMOTE_AUTH_DEFAULT_PERMISSIONS = REMOTE_AUTH_DEFAULT_PERMISSIONS

------------------------------

## Steps to Reproduce

1.
2.
3.
4.

## Environment
**OS:**
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**

**Comment by robertsewter** [comment] 2022-07-23 20:19
Duplicate of #36 I think. Same issue here.

**Closed** 2023-04-07 21:04 UTC
Labels: no-issue-activity, closed-issue-activity
